package cocona20xx.novahook.api;

import lombok.Getter;
import net.minecraft.util.Identifier;

import java.util.Objects;

/**
 * Data class used by override suppliers and override request mixin methods to specify what texture an override is being requested for.
 */
public final class OverrideToken {
    public static final Identifier MULTI_EYE_POINTER_ID = new Identifier("novahook", "autogenerated_eye"); //DOES NOT ACTUALLY POINT TO A TEXTURE
    @Getter private final TokenTypes ofTokenType;
    @Getter private final Identifier ofTextureId;
    @Getter private final Identifier ofMobTypeId;
    public enum TokenTypes {base_layer, eye_layer, feature}

    public OverrideToken(Identifier ofMobTypeId, Identifier ofTextureId, TokenTypes ofTokenType){
        this.ofTokenType = ofTokenType;
        this.ofTextureId = ofTextureId;
        this.ofMobTypeId = ofMobTypeId;
    }

    @Override
    public boolean equals(Object obj) {
        if(obj instanceof OverrideToken toCheck){
            return Objects.equals(toCheck.ofMobTypeId, this.ofMobTypeId) && Objects.equals(toCheck.ofTokenType, this.ofTokenType) && Objects.equals(toCheck.ofTextureId, this.ofTextureId);
        } else return false;
    }
}
