name: on-release
on:
  release:
    types: [created]
jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          16,    # Minimum supported by Minecraft
          17,    # Current Java LTS
        ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: publish release files
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} 
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*;LICENSE'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: publish release package
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} 
        run: gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
